apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx1
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
      nodeSelector:
        test: nginx1
